apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bot-base
- configmap.yaml
commonLabels:
  component: openeuler-review
patches:
- path: deployment.json
  target:
    group: apps
    kind: Deployment
    name: deployment
    version: v1
nameSuffix: -openeuler-review
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee-openeuler-review
  newTag: master-cd26a26-dirty
