apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics-test
  newTag: 61358cce175755713af7e836568e51e08b19f45c
kind: Kustomization
namespace: xihe-test-v2
resources:
- xihe-statistics-ingress.yaml
- xihe-statistics-service.yaml
- xihe-statistics-secret.yaml
- xihe-statistics-deployment.yaml
