apiVersion: apps/v1
kind: Deployment
metadata:
  name: xihe-statistics-deployment
  namespace: xihe-test-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xihe-statistics
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xihe-statistics
    spec:
      containers:
      - env:
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              key: config_path
              name: xihe-statistics-secret
        - name: GITLAB_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: GITLAB_ENDPOINT
              name: xihe-statistics-secret
        - name: GITLAB_GRAPHQL_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: GITLAB_GRAPHQL_ENDPOINT
              name: xihe-statistics-secret
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              key: GITLAB_TOKEN
              name: xihe-statistics-secret
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-statistics-test:c5ebfdafa8903c49ee050404b337ea517481c316
        imagePullPolicy: IfNotPresent
        args:
        - --port=8080
        - --config-file=/conf/xihe-statistics/config.yaml
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        name: xihe-statistics
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 2000Mi
          requests:
            cpu: 1000m
            memory: 1000Mi
        volumeMounts:
        - mountPath: /conf/xihe-statistics/config.yaml
          name: secret-config
          subPath: config_yaml
      volumes:
      - name: secret-config
        secret:
          secretName: xihe-statistics-secret
