apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      repo_plugins:
        zengchen1024/repo-test:
        - checkpr

      plugins:
      - name: checkpr
        endpoint: http://service-checkpr.robot-gitee.svc.cluster.local:8888
        events:
        - "Merge Request Hook"
