apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: xihe-new
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }

    server {
      # listen 443 ssl;
      # server_name localhost;
      # charset utf-8;

      listen 8080;
      server_name localhost;
      charset utf-8;
      limit_conn perserver 50;
      if ($request_method = 'OPTIONS') {
        return 401;
      }

      location / {
        location /assets {
          # publish every two weeks
          expires 14d;
          add_header Cache-Control public;
        }
        location / {
          add_header Cache-Control no-cache;
          proxy_set_header Host $host;
          try_files $uri /index.html;
        }

        root /usr/share/nginx/html;
        index /index.html;
        proxy_set_header Host $host;
        #   error_page 404 /404.html;
      }

      location ^~ /server/ {
        proxy_pass http://xihe-backend-service.xihe-new.svc.cluster.local/api/v1/ ;
        proxy_read_timeout 3600s;
        proxy_connect_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
      }

      location ^~ /api/ {
        proxy_pass http://xihe-backend-service.xihe-new.svc.cluster.local ;
      }

      location ^~ /oneid/ {
        proxy_pass https://xiheapi.osinfra.cn/oneid/ ;
      }

      location ^~ /repo/ {
        proxy_pass https://gitlab.openeuler.sh/api/v4/ ;
      }

      location /gitlab-lfs {
        proxy_pass https://xihe-production-obs.obs.cn-north-4.myhuaweicloud.com ;
      }

      location /obs-big-model/ {
        proxy_pass https://big-model-deploy.obs.cn-central-221.ovaijisuan.com/;
      }

      location /obs-xihe-avatar/ {
        proxy_pass https://obs-xihe-beijing4.obs.cn-north-4.myhuaweicloud.com/;
      }

      location /statistics/ {
        proxy_pass https://xihe-statistics.mindspore.cn/;
      }

      error_page 500 501 502 503 504 505 /500.html;
      error_page 401 /401.html;
      error_page 404 /404.html;

      location = /401.html {
        root /usr/share/nginx/html;
      }

      location = /404.html {
        root /usr/share/nginx/html;
      }

      location = /500.html {
        root /usr/share/nginx/html;
      }
    }