apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    commands_endpoint: "https://prow.osinfra.cn/gitee-deck/command-help?repo="
    doc: "You can get details about the review process of pull-request at [**here**](https://gitee.com/I-am-a-robot/community/raw/master/pr_review.svg)"
    maintainers:
      mindspore/docs:
      - gemini524
      mindspore/mindspore:
      - baochong

    config_items:
    - repos:
      - mindspore/docs
      - mindspore/mindformers
      - mindspore/mindinsight
      need_welcome: true
      cla_label: "mindspore-cla/yes"
      review:
        number_of_approvers: 1
        total_number_of_approvers: 1
        total_number_of_reviewers: 1
    - repos:
      - mindspore/mindspore
      - mindspore/xihe-website
      - mindspore/Xihe-docs
      - mindspore/website-v2
      - mindspore/website-docs
      need_welcome: true
      cla_label: "mindspore-cla/yes"
      labels_for_basic_ci_passed:
      - ci-pipeline-passed
      review:
        number_of_approvers: 1
        total_number_of_approvers: 2
        total_number_of_reviewers: 1
        endpoint_to_recommend_reviewer: https://omapi.test.osinfra.cn/query/reviewer/recommend
        
    - repos:
        - mindspore/graphlearning
      need_welcome: true
      cla_label: "mindspore-cla/yes"
      labels_for_basic_ci_passed:
        - ci-pipeline-passed
      review:
        number_of_approvers: 1
        total_number_of_approvers: 2
        total_number_of_reviewers: 2
        endpoint_to_recommend_reviewer: https://omapi.test.osinfra.cn/query/reviewer/recommend    
        
