apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mindspore-summary-new
resources:
- mindspore-summary-deployment.yaml
- mindspore-summary-ingress.yaml
- mindspore-summary-service.yaml
- oauth-proxy.yaml
- namespace.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/summary
  newTag: v1.0.20221230221504
