apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: xihe-test-v2
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: hook-delivery
        args:
        - --port=8000
        - --config-file=/app/conf/xihe-gitlab/app_config/config.yaml
        - --hmac-secret-file=/app/conf/xihe-gitlab/hmac
        - --kafkamq-config-file=/app/conf/xihe-gitlab/kafka
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/conf/xihe-gitlab/hmac
          subPath: SYSTEMHOOK_HMAC
          name: secret-volume
        - mountPath: /app/conf/xihe-gitlab/kafka
          subPath: KAFKA_ADDRESS
          name: secret-volume
        - mountPath: /app/conf/xihe-gitlab/app_config/
          name: app-config
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: xihe-secret
      - name: app-config
        configMap:
          name: configmap-hook-delivery
