apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: robot-gitee
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: repo-owners-cache
        args:
        - --endpoint=http://service-repo-file-cache.robot-gitee.svc.cluster.local:80/v1/file/
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8888
            name: http
            protocol: TCP
