apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  kubernetes.ops.cluster: mindspore-cn4-x86-cluster
  kubernetes.ops.email: 775517776@qq.com
  kubernetes.ops.os.base: debian
  kubernetes.ops.owner: chenyang
  kubernetes.ops.region: beijing
kind: Kustomization
namespace: mindspore-doc-search
resources:
- namespace.yaml
- doc-search-ingress.yaml
- doc-search-service.yaml
- doc-search-secret.yaml
- doc-search-deployment.yaml
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/docs-search
  newTag: v1.0.20230707205441
