apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - ascend/canndev
      - ascend/metadef
      - ascend/parser
      - ascend/tensorflow
      commits_threshold: 1
      clear_labels:
      - ci-pipeline-passed