apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      topic: xihe_gitlab_new
      user_agent: Robot-Gitlab-Hook-Delivery
      access_endpoint: http://service-access.xihe-new.svc.cluster.local:8000/gitlab-access
      concurrent_size: 1
