apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: repo-tools-ingress
spec:
  tls:
    - hosts:
        - tools.mindspore.cn
      secretName: repo-tools-tls
  rules:
    - host: tools.mindspore.cn
      http:
        paths:
          - backend:
              serviceName: mindspore-service
              servicePort: 80
            path: /
