apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - ascend/playground
      - ascend/pyge
      - ascend/slurm-atlas-plugin
      - ascend/tools
      - ascend/community
      - ascend/ais-bench
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."

      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."

      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."
    - repos:
      - ascend/canndev
      merge_method: squash
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."

      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."

      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."

      - label: ci-pipeline-passed
        person: turing_project
        tips_if_missing: "Please wait for the CI test to be completed."
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."  
        
    - repos:
      - ascend/Asight
      - ascend/torchair
      merge_method: squash
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."
      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."
      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."
      - label: ci-pipeline-passed
        person: turing_project
        tips_if_missing: "Please wait for the CI test to be completed."
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."  
        
    - repos:
      - ascend/cann_op_contrib
      - ascend/vision
      merge_method: squash
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."
      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."
      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."
       
    - repos:
      - ascend/modelzoo
      - ascend/samples
      - ascend/ModelZoo-PyTorch
      - ascend/ModelZoo-TensorFlow
      - ascend/op-plugin
      - ascend/ascend-op-common-lib
      - ascend/ascend-transformer-acceleration
      - ascend/ascend-inference
      - ascend/ascend-faster-transformer
      - ascend/ascend-inference-ptplugin
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."

      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."

      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."

      - label: ci-pipeline-passed
        tips_if_missing: "Please wait for the CI test to be completed."
        person: turing_project
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."
    
    - repos:
      - ascend/metadef
      - ascend/tensorflow
      - ascend/parser
      merge_method: squash
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."

      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."

      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."

      - label: ci-pipeline-passed
        tips_if_missing: "Please wait for the CI test to be completed."
        person: turing_project
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."

    - repos:
      - ascend/cann-benchmark
      - ascend/mindstudio
      - ascend/mindxdl-deploy
      - ascend/pytorch
      - ascend/pytorch-develop
      - ascend/apex
      - ascend/apex-develop
      - ascend/mindxsdk-referenceapps
      - ascend/ascend-docker-image
      - ascend/ascend-deployer
      - ascend/AtlasShareDS
      - ascend/ascend-pae
      - ascend/mindx-science
      - ascend/ascend_community_projects
      - ascend/ascend-opencv
      - ascend/ascend-industrial
      - ascend/msadvisor
      - ascend/ait
      - ascend/att
      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."

      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."

      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."

      - label: ci-pipeline-passed
        tips_if_missing: "Please wait for the CI test to be completed."
        person: atlasaccount
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."
        
    - repos:
      - ascend/ascend-devkit-imager
      - ascend/ascend-devkit-model-adapter

      labels:
      - label: lgtm
        tips_if_missing: "Please wait for reviewers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add lgtm label manually. Please remove it and wait for reviewers to review your codes."
        
      - label: approved
        tips_if_missing: "Please wait for approvers to review the code."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add approved label manually. Please remove it and wait for approvers to review your codes."
        
      - label: ascend-cla/yes
        tips_if_missing: "Please sign CLA. If you have done, comment /check-cla to recheck again."
        person: I-am-a-robot
        tips_if_added_by_others: "You can't add ascend-cla/yes label manually. Please comment /check-cla to verify it again."
        
      - label: ci-pipeline-passed
        tips_if_missing: "Please wait for the CI test to be completed."
        person: atlasaccount
        tips_if_added_by_others: "You can't add ci-pipeline-passed label manually. Please remove it and wait for the CI test to be completed."