apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
  name: xihe-ingress
  namespace: xihe-dev
spec:
  tls:
    - hosts:
        - xihe-dev.test.osinfra.cn
      secretName: xihe-tls
  rules:
    - host: xihe-dev.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: xihe-website-service
              servicePort: 80
            path: /