resources:
- xihe-website.yaml
- namespace.yaml
- secret.yaml
- ingress.yaml
- configmap.yaml
- xihe-server.yaml
- xihe-message-server.yaml
- hook-delivery
- hook-dispatcher
- access
- sync-repo
- training-center-huaweicloud
namespace: xihe-dev
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-message-server
  newTag: 70931b8886b748e1e57340e2f15059911a5c49f9
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-server
  newTag: 268eb31af7f3a1127a040043624e21588c604e9a
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-website-test
  newTag: 072557f0fc3820b9092b7d46b2d7d937dbdbdfc1
