apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: xihe-new
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: internal-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe:latest
        imagePullPolicy: IfNotPresent
        args:
        - --port=8000
        - --config-file=/opt/app/conf/config.yaml
        - --enable_debug=false
        env:
        - name: MONGODB_NAME
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: MONGODB_NAME
        - name: MONGODB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: MONGODB_CONNECTION
        - name: MONGODB_CERT
          valueFrom:
            secretKeyRef:
              key: MONGODB_CERT
              name: xihe-secret
        - name: PGSQL_HOST
          valueFrom:
            secretKeyRef:
              name: xihe-statistics-secret
              key: PGSQL_HOST
        - name: PGSQL_USER
          valueFrom:
            secretKeyRef:
              name: xihe-statistics-secret
              key: PGSQL_USER
        - name: PGSQL_PWD
          valueFrom:
            secretKeyRef:
              name: xihe-statistics-secret
              key: PGSQL_PWD
        - name: PGSQL_NAME
          valueFrom:
            secretKeyRef:
              name: xihe-statistics-secret
              key: PGSQL_NAME
        - name: PGSQL_PORT
          valueFrom:
            secretKeyRef:
              name: xihe-statistics-secret
              key: PGSQL_PORT
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /opt/app/conf
          name: config
        - mountPath: /opt/mongo/ca.crt
          name: secret
          subPath: ca-cert
      volumes:
      - name: config
        configMap:
          name: configmap-internal-server
      - name: secret
        secret:
          secretName: xihe-secret
