resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- config.yaml
- rbac.yaml
commonLabels:
  app: covid-shanghai-server
  owner: tommylike
commonAnnotations:
  email: tommylikehu@gmail.com
namespace: covid-shanghai
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/covidshanghai
  newTag: d03e2880812843974d3576226df43e17705efd11
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/landscape
  newTag: f4b6ccbfc6a4494be5b77ab201194b35d6973271
