apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      topic: xihe-gitlab-test-v2
      user_agent: Robot-Gitlab-Hook-Delivery
      access_endpoint: http://service-access.xihe-test-v2.svc.cluster.local:8000/gitlab-access
      concurrent_size: 10
