apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: inference-evaluate
        args:
        - --port=8888
        - --config-file=/app/conf/xihe-gitlab/app_config/config.yaml
        - --enable_debug=true
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/conf/xihe-gitlab/app_config/
          name: app-config
          readOnly: true
        - mountPath: /app/conf/xihe-gitlab/kube/config
          name: kubeconfig
          subPath: cluster_kubeconfig
        env:
        - name: HW_OBS_AK
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: HW_OBS_AK
        - name: HW_OBS_SK
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: HW_OBS_SK
        - name: HW_OBS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: HW_OBS_ENDPOINT
        - name: HW_OBS_BUCKET
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: HW_OBS_BUCKET
        - name: GITLAB_HOST
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: GITLAB_HOST
        - name: JUPYTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: JUPYTER_TOKEN
        - name: CLOUD_CRD_IMAGE
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: CLOUD_CRD_IMAGE
        - name: CLOUD_CRD_CPU
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: CLOUD_CRD_CPU
        - name: CLOUD_CRD_MEMORY
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: CLOUD_CRD_MEMORY
      volumes:
      - name: app-config
        configMap:
          name: configmap-inference-evaluate
      - name: kubeconfig
        secret:
          secretName: xihe-cluster-secret-inference-evaluate
