apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- secret.yaml
commonLabels:
  component: inference-evaluate
nameSuffix: -inference-evaluate
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-inference-evaluate
  newTag: main-479415e
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-inference-evaluate
  newTag: v1.0.20230428102306
