apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
commonLabels:
  component: hook-dispatcher
nameSuffix: -hook-dispatcher
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-hook-dispatcher
  newTag: main-4cfbf8e
