apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - ascend
      require_self_approval: true      
    - repos:
      - ascend/canndev
      - ascend/cann_op_contrib
      - ascend/vision
      - ascend/Asight
      - ascend/metadef
      - ascend/parser
      - ascend/pytorch
      - ascend/pytorch-develop
      - ascend/mindstudio
      - ascend/msadvisor
      require_self_approval: true
