apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - ascend
      excluded_repos:
      - ascend/pytorch
      require_self_approval: true      

    - repos:
      - ascend/canndev
      - ascend/cann_op_contrib
      - ascend/torchair
      - ascend/vision
      - ascend/Asight
      - ascend/metadef
      - ascend/parser
      - ascend/pytorch-develop
      - ascend/mindstudio
      - ascend/msadvisor
      - ascend/op-plugin
      - ascend/ascend-faster-transformer
      - ascend/ascend-inference-ptplugin
      - ascend/ascend-devkit-imager
      - ascend/ascend-devkit-model-adapter
      - ascend/ascend-transformer-acceleration
      - ascend/ascend-op-common-lib
      - ascend/ascend-inference
      require_self_approval: true
