resources:
- xihe-website.yaml
- namespace.yaml
- secret.yaml
- ingress.yaml
- configmap.yaml
- xihe-server.yaml
- xihe-inference-evaluate.yaml
- internal-server
- message-server
- hook-delivery
- hook-dispatcher
- access
- sync-repo
- training-center-huaweicloud
- inference-evaluate
namespace: xihe-test-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/xihe-inference-evaluate
  newTag: v1.0.20221104110303
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-server
  newTag: d119faf8892e88699e7a8f02f2311b5db7a5fb53
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-website-test
  newTag: 66b80e5a6fbf24fe05ea236accc230836bb73c19
