resources:
- xihe-website.yaml
- namespace.yaml
- secret.yaml
- ingress.yaml
- configmap.yaml
- xihe-server.yaml
- xihe-inference-evaluate.yaml
- internal-server
- message-server
- hook-delivery
- hook-dispatcher
- access
- sync-repo
- training-center-huaweicloud
namespace: xihe-test-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/mindspore/xihe-inference-evaluate
  newTag: v1.0.20221031194604
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-server
  newTag: 8b2041ba405689c0ca4780a4800d464c82f27755
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-website-test
  newTag: f577eaa2f4d0d88b7c039ae70ef61536b664a7dc
