resources:
- xihe-website.yaml
- namespace.yaml
- secret.yaml
- ingress.yaml
- configmap.yaml
- xihe-server.yaml
namespace: xihe-test-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-server
  newTag: 67db012721327ad87392755fc17161a1030dcb0f
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-website-test
  newTag: f90f7c98dcd504cc3e0c935f972a11e66547990a
