apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: xihe-new
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sync-repo
        args:
        - --port=8000
        - --config-file=/app/conf/xihe-gitlab/app_config/config.yaml
        - --kafkamq-config-file=/app/conf/xihe-gitlab/kafka
        - --enable_debug=true
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /app/conf/xihe-gitlab/kafka
          subPath: KAFKA_ADDRESS
          name: secret-volume
        - mountPath: /app/conf/xihe-gitlab/app_config/
          name: app-config
          readOnly: true
        - mountPath: /workspace
          name: data-volume
        env:
        - name: ACCESS_HMAC
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: SYSTEMHOOK_HMAC
        - name: HW_OBS_AK
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: HW_OBS_AK
        - name: HW_OBS_SK
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: HW_OBS_SK
        - name: HW_OBS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: HW_OBS_ENDPOINT
        - name: HW_OBS_BUCKET
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: HW_OBS_BUCKET
        - name: MYSQL_CONN
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: MYSQL_CONN
        - name: GITLAB_TOKEN
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: GITLAB_TOKEN
        - name: GITLAB_MINDSPORE_HOST
          valueFrom:
            secretKeyRef:
              name: xihe-secret
              key: GITLAB_MINDSPORE_HOST
      volumes:
      - name: app-config
        configMap:
          name: configmap-sync-repo
      - name: data-volume
        persistentVolumeClaim:
          claimName: xihe-sync-repo-pvc-sync-repo
      - name: secret-volume
        secret:
          secretName: xihe-secret
