apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    syncrepo:
      access_endpoint: http://service-hook-delivery.xihe-test-v2.svc.cluster.local:8000/gitlab-hook
      access_hmac: "${ACCESS_HMAC}"
      topic: xihe-gitlab-test-v2
      user_agent: Robot-Gitlab-Hook-Delivery
      size_of_workspace: 40
      average_repo_size: 2

    obs: 
      obsutil_path: /opt/app/obsutil
      access_key: "${HW_OBS_AK}"
      secret_key: "${HW_OBS_SK}"
      endpoint: "${HW_OBS_ENDPOINT}"
      bucket: "${HW_OBS_BUCKET}"
    
    app:
      work_dir: "/opt/app/workspace"
      sync_file_shell: /opt/app/sync_files.sh
      lfs_path: gitlab-lfs
      repo_path: xihe-repos
      commit_file: synced_commit

    mysql:
      conn: "${MYSQL_CONN}"
      conn_max_life_time: 1
      table_name: "dataset_model"

    gitlab:
      token: "${GITLAB_TOKEN}"
      host: "${GITLAB_INNER_HOST}"
