apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
commonLabels:
  component: sync-repo
nameSuffix: -sync-repo
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/robot-gitlab-sync-repo
  newTag: main-411716
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/robot-gitlab-sync-repo
  newTag: dev-552ebd
