apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/big-model-finetune
  newTag: dev-8ed384
kind: Kustomization
namespace: xihe-test-v2
resources:
- service.yaml
- big-model-finetune-deployment.yaml
- big-model-finetune-secret.yaml
