---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/limit-rpm: "400"
  name: openeuler-ipb-production-ingress
  namespace: openeuler-ipb
spec:
  tls:
    - hosts:
        - ipb.osinfra.cn
      secretName: openeuler-ipb-production-tls
  rules:
    - host: ipb.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: openeuler-ipb-service
              servicePort: 80
            path: /
