resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
namespace: openeuler-ipb
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-ipb-test
  newTag: 51ff2c921c0555acc3eb1f34ea9026852247ce76
