apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
#    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: repo-ingress
spec:
  tls:
    - hosts:
        - download-new.mindspore.cn
      secretName: download-secrets
  rules:
    - host: download.mindspore.cn
      http:
        paths:
          - backend:
              serviceName: repo-service
              servicePort: 80
            path: /
