apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Content-Type-Options "nosniff";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Frame-Options "DENY";
      add_header Content-Security-Policy "script-src 'self' *.baidu.com ers.baidu.com 'unsafe-inline' 'unsafe-eval'; object-src 'none'; frame-src *.mindspore.cn";
      add_header Cache-Control "no-cache";
      add_header Pragma "no-cache";
  name: xihe-ingress
  namespace: xihe-test-v2
spec:
  tls:
    - hosts:
        - xihe2.test.osinfra.cn
      secretName: xihe-tls
  rules:
    - host: xihe2.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: xihe-website-service
              servicePort: 80
            path: /