apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bot-base
- configmap.yaml
commonLabels:
  component: opengauss-review
patches:
- path: deployment.json
  target:
    group: apps
    kind: Deployment
    name: deployment
    version: v1
patchesStrategicMerge:
- secrets.yaml
nameSuffix: -opengauss-review
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee-opengauss-review
  newTag: master-02ced29
