apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- secrets.yaml
- service.yaml
commonLabels:
  component: repo-file-cache
nameSuffix: -repo-file-cache
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/repo-file-cache
  newTag: master-1e99029
