apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - src-openeuler
      community_name: src-openeuler
      community_repo: community
      branch: master
      command_link: https://gitee.com/openeuler/community/blob/master/en/sig-infrastructure/command.md

