apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bot-base
- configmap.yaml
commonLabels:
  component: openeuler-welcome
patches:
- path: deployment.json
  target:
    group: apps
    kind: Deployment
    name: deployment
    version: v1
nameSuffix: -openeuler-welcome
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-github-openeuler-welcome
  newTag: main-74f8180
