apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /admin {
        deny all;
      }
    nginx.ingress.kubernetes.io/custom-http-errors: "500"
  name: mailweb-ingress
spec:
  tls:
    - hosts:
        - mailweb.mindspore.cn
      secretName: mindspore-mailweb-tls
  rules:
    - host: mailweb.mindspore.cn
      http:
        paths:
          - backend:
              serviceName: mailman-web-service
              servicePort: 80
            path: /
