apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../repo-watcher
- configmap.yaml
commonLabels:
  component: repo-watcher-src-oepkgs
patches:
- path: deployment.json
  target:
    group: apps
    kind: Deployment
    name: deployment
    version: v1
nameSuffix: -repo-watcher-src-oepkgs
