apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
commonLabels:
  component: training-center-huaweicloud
nameSuffix: -training-center-huaweicloud
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-training-center
  newTag: main-7ab5c52
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-training-center
  newTag: v1.0.20230608091425
