apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    training_endpoint: http://service-training-center-huaweicloud.xihe-test-v2.svc.cluster.local:8888/api/v1/training
    mongodb:
      db_conn: "${MONGODB_CONNECTION}"
      db_name: "${MONGODB_NAME}"
      collections:
        project: project
        model: model
        dataset: dataset 
        user: user
        login: login
        like: like
        activity: activity
        tag: tag
        luojia: luojia
        training: training
        evaluate: evaluate
        inference: inference
        aiquestion: aiquestion
        competition: competition

    domain:
      covers:
      - "1"
      - "2"
      - "3"
      - "4"

      protocols:
      - "apache 2.0"
      - "mit"
      - "cc-by-sa-3.0"
      - "afl-3.0"
      - "cc-by-sa-4.0"
      - "lgpl-3.0"
      - "lgpl-lr"
      - "cc-by-nc-3.0"
      - "lgpl"
      - "bsd-2-clause"
      - "ecl-2.0"
      - "cc-by-nc-sa-4.0"
      - "cc-by-nc-4.0"
      - "gpl-3.0"
      - "other"
      - "cc0-1.0"
      - "cc"
      - "bsd-3-clause"
      - "agpl"
      - "wtfpl"
      - "artistic-2.0"
      - "postgresql"
      - "bigscience-bloom-rail-1.0"
      - "gpl-2.0"
      - "isc"
      - "bsd-3"
      - "equpl-1.1"
      - "academic-free-license-v3.0"
      - "pddl"
      - "bsd-3-clause-clear"
      - "mpl-2.0"

      project_type:
      - "Gradio"
      - "Static"

      training_platform:
      - "ModelArts"

    mq:
      address: "${KAFKA_ADDRESS}"
      topics:
        fork: "xihe_fork_test"
        like: "xihe_like_test"
        evaluate: "xihe_evaluate_test"
        training: "xihe_training_test"
        inference: "xihe_inference_test"
        following: "xihe_following_test"
        submission: "xihe_submission_test"
        related_resource: "xihe_related_resource_test"

    evaluate:
      endpoint: http://service-inference-evaluate.xihe-test-v2.svc.cluster.local:8888

    inference:
      endpoint: http://service-inference-evaluate.xihe-test-v2.svc.cluster.local:8888
