apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: heliosserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helios-server
      component: vote-server
  template:
    metadata:
      labels:
        app: helios-server
        component: vote-server
    spec:
      nodeSelector:
        helios: "true"
      containers:
        - name: helios-server
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/helios-server/helios-voting:master-0944cae
          volumeMounts:
            - mountPath: /app/helios-server/helios/migrations
              name: helios-data-volume
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
          env:
            - name: GH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GH_CLIENT_ID
                  name: helios-server-secrets
            - name: GH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GH_CLIENT_SECRET
                  name: helios-server-secrets
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: helios-server-secrets
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: helios-server-secrets
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      volumes:
        - name: helios-data-volume
          persistentVolumeClaim:
            claimName: helios-data-volume
