apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - service.yaml
  - pvc.yaml
  - namespace.yaml
namespace: heliosserver
images:
  - name: swr.cn-north-4.myhuaweicloud.com/opensourceway/helios-server/helios-voting
    newTag: master-87a24f1