apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
- cla
- welcome
- review
- label
commonLabels:
  app: infrastructure-robot-github
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: robot-github-openeuler
