apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    clients:
    - platform: gitee
      grpc_endpoint: service-sync-file-server.robot-gitee.svc.cluster.local:8888

    sync_files:
    - platform: gitee
      org_repos:
      - org: mindspore
      - org: opengauss
        repos:
        - tc
      - org: openeuler
        repos:
        - community
      file_names:
      - OWNERS
