resources:
  - ingress.yaml
  - namespace.yaml
  - nginx-purge.yaml
  - poetry-service.yaml
  - text-generation-service.yaml
  - meetingserver-service.yaml
commonLabels:
  app: mindspore-api
commonAnnotations:
  owner: tommylikehu
  email: "tommylikehu@gmail.com"
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: poetry-service
    path: selector.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: text-generation-service
    path: selector.yaml
namespace: mindspore-api
