apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
  namespace: source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      nodeSelector:
        gitlab: "true"
      containers:
      - name: gitlab
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/sameersbn-gitlab:15.2.2
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: GITLAB_TIMEZONE
          value: Asia/Shanghai
        - name: GITLAB_SECRETS_DB_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-secrets-db-key-base
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-secrets-secret-key-base
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-secrets-otp-key-base
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-root-password
        - name: GITLAB_ROOT_EMAIL
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-root-email
        - name: GITLAB_EMAIL
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-email
        - name: GITLAB_EMAIL_REPLY_TO
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: gitlab-email-reply-to
        - name: GITLAB_INCOMING_EMAIL_ADDRESS
          value: reply@feishu.cn
        - name: GITLAB_HOST
          value: source-xihe.mindspore.cn
        - name: GITLAB_PORT
          value: "80"
        - name: GITLAB_SSH_PORT
          value: "22"
        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"
        - name: GITLAB_BACKUP_SCHEDULE
          value: daily
        - name: GITLAB_BACKUP_TIME
          value: 01:00

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: postgres-host
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: postgres-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: postgres-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: postgres-name
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: redis-password
        - name: SMTP_ENABLED
          value: "true"
        - name: SMTP_DOMAIN
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: smtp-domain
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: smtp-host
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: smtp-port
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: smtp-user
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: smtp-password
        - name: SMTP_STARTTLS
          value: "true"
        - name: SMTP_AUTHENTICATION
          value: login

        - name: IMAP_ENABLED
          value: "true"
        - name: IMAP_HOST
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: imap-host
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: imap-user
        - name: IMAP_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab-secrets
              key: imap-password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "true"
        
        - name: GITLAB_LFS_ENABLED
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_enable
        - name: GITLAB_LFS_OBJECTS_DIR
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_objects_dir
        - name: GITLAB_LFS_OBJECT_STORE_ENABLED
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_object_store_enabled
        - name: GITLAB_LFS_OBJECT_STORE_PROXY_DOWNLOAD
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_object_store_proxy_download
        - name: GITLAB_LFS_OBJECT_STORE_REMOTE_DIRECTORY
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_object_store_remote_directory
        - name: GITLAB_LFS_OBJECT_STORE_CONNECTION_PROVIDER
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_provider
        - name: GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_REGION
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_aws_region
        - name: GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_aws_access_key_id
        - name: GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_aws_secret_access_key
        - name: GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_object_aws_endpoint
        - name: GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_SIGNATURE_VERSION
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_object_aws_signature_version
        - name: GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_HOST
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_object_aws_host
        - name: GITLAB_LFS_OBJECT_STORE_CONNECTION_AWS_PATH_STYLE
          valueFrom:
            secretKeyRef:
              name: gitlab-lfs-secrets
              key: gitlab_lfs_object_aws_path_style
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        resources:
          requests:
            cpu: 10000m
            memory: 20000Mi
          limits:
            cpu: 5000m
            memory: 10000Mi
        volumeMounts:
        - mountPath: /home/git/data
          name: gitlab-data
        - mountPath: /home/git/gitlab-shell/hooks/
          name: gitlab-hooks-data
        - mountPath: /etc/docker-gitlab/runtime/functions
          name: configmap
          subPath: functions
        - mountPath: /etc/docker-gitlab/runtime/config/gitlabhq/resque.yml
          name: configmap
          subPath: resque.yml
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data-volume
      - name: gitlab-hooks-data
        persistentVolumeClaim:
          claimName: gitlab-hooks-volume
      - name: configmap
        configMap:
          name: gitlab-configmap
          defaultMode: 436
