apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "5G"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location /api/graphql {
        return 403;
      }
      location /.well-known/openid-configuration {
        return 403;
      }
      location /oauth/discovery/keys {
        return 403;
      }
      location /users/sign_in {
        return 403;
      }
      location /users/sign_up {
        return 403;
      }
  name: gitlab-ingress
  namespace: source
spec:
  tls:
    - hosts:
        - source-xihe.mindspore.cn
      secretName: gitlab-xihe-tls
  rules:
    - host: source-xihe.mindspore.cn
      http:
        paths:
          - backend:
              serviceName: gitlab-service
              servicePort: 80
            path: /