apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: robot-gitee-openeuler
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: name
        args:
        - --gitee-token-path=/app/conf/robot-gitee/robot_token
        - --config-file=/app/conf/robot-gitee/app_config/config.yaml
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /app/conf/robot-gitee/robot_token
          subPath: robot-token
          name: secret-volume
        - mountPath: /app/conf/robot-gitee/app_config/
          name: app-config
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: secret-robot-token
      - name: app-config
        configMap:
          name: config
