apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    access:
      plugins:
      - name: sync-repo
        endpoint: http://service-sync-repo.xihe-test-v2.svc.cluster.local:8000/gitlab-hook
        events:
        - "Push Hook"

