apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crontab.yaml
- configmap.yaml
commonLabels:
  component: scavenger
nameSuffix: -scavenger
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee-scavenger
  newTag: master-2275d2b