apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
- sweepstakes
- checkpr
- lgtm
- associate
- assign
- approve
- cla
commonLabels:
  app: infrastructure-robot-gitee
commonAnnotations:
  email: chenzeng765@163.com
  owner: chenzeng
namespace: robot-gitee-openlookeng
