apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config:
      watching_files:
        org: newwanghao
        repo: community
        branch: master
        repo_org: src-newwanghao
        sig_file_path: sig/sigs.yaml
        sig_dir: sig
      concurrent_size: 2000
      enable_creating_obs_meta_project: true
      interval: 3
      obs_meta_project:
        obs_repo:
          org: newwanghao
          repo: release-management
          branch: master
        project_dir: master/openEuler-Factory
        project_file_name: pckg-mgmt.yaml

